from __future__ import annotations

from dataclasses import dataclass


NIFTY_50 = (
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO",
    "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL", "CIPLA", "COALINDIA",
    "DRREDDY", "EICHERMOT", "ETERNAL", "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE",
    "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "INDUSINDBK", "INFY",
    "ITC", "JIOFIN", "JSWSTEEL", "KOTAKBANK", "LT", "M&M", "MARUTI", "NESTLEIND",
    "NTPC", "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", "SBIN", "SHRIRAMFIN",
    "SUNPHARMA", "TATACONSUM", "TATAMOTORS", "TATASTEEL", "TCS", "TECHM", "TITAN",
    "TRENT", "ULTRACEMCO", "WIPRO",
)

NIFTY_100_EXTRA = (
    "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "BAJAJHLDNG",
    "BANKBARODA", "BOSCHLTD", "BPCL", "BRITANNIA", "CANBK", "CHOLAFIN",
    "DABUR", "DIVISLAB", "DLF", "DMART", "GAIL", "GODREJCP", "HAL", "HAVELLS",
    "ICICIGI", "ICICIPRULI", "INDIGO", "IOC", "IRFC", "JINDALSTEL", "JSWENERGY",
    "LICI", "LODHA", "LTIM", "MOTHERSON", "NAUKRI", "NHPC", "PIDILITIND", "PNB",
    "RECLTD", "SHREECEM", "SIEMENS", "TATAPOWER", "TORNTPHARM", "TVSMOTOR",
    "UNIONBANK", "UNITDSPR", "VBL", "VEDL", "ZYDUSLIFE",
)

NIFTY_200_EXTRA = (
    "ABCAPITAL", "ABFRL", "ACC", "ALKEM", "APLAPOLLO", "ASHOKLEY", "ASTRAL",
    "AUBANK", "AUROPHARMA", "BALKRISIND", "BANDHANBNK", "BDL", "BHARATFORG",
    "BIOCON", "BSE", "CGPOWER", "COLPAL", "CONCOR", "CUMMINSIND", "DELHIVERY",
    "DIXON", "FEDERALBNK", "FORTIS", "GLENMARK", "GMRINFRA", "GODREJPROP",
    "HDFCAMC", "HINDPETRO", "HINDZINC", "HUDCO", "IDFCFIRSTB", "IEX", "INDHOTEL",
    "INDIANB", "INDUSTOWER", "IRB", "IREDA", "JSWINFRA", "KPITTECH", "LICHSGFIN",
    "LTF", "LUPIN", "MANKIND", "MAXHEALTH", "MAZDOCK", "MFSL", "MPHASIS",
    "NMDC", "OBEROIRLTY", "OFSS", "OIL", "PAGEIND", "PATANJALI", "PAYTM",
    "PERSISTENT", "PETRONET", "PHOENIXLTD", "PIIND", "POLICYBZR", "POLYCAB",
    "PRESTIGE", "RVNL", "SAIL", "SBICARD", "SRF", "SUPREMEIND", "SUZLON",
    "TATACHEM", "TATAELXSI", "TATATECH", "TIINDIA", "TORNTPOWER", "UNOMINDA",
    "UPL", "YESBANK",
)

FNO_EXTRA = (
    "AARTIIND", "ABBOTINDIA", "ATGL", "BATAINDIA", "BERGEPAINT", "BSOFT",
    "CAMS", "CDSL", "CESC", "COFORGE", "CYIENT", "DALBHARAT", "EXIDEIND",
    "GRANULES", "GUJGASLTD", "HINDCOPPER", "IDEA", "IIFL", "IRCTC", "KALYANKJIL",
    "KEI", "LAURUSLABS", "MANAPPURAM", "MCX", "NATIONALUM", "NBCC", "NYKAA",
    "PFC", "POONAWALLA", "RBLBANK", "SONACOMS", "SYNGENE", "TITAGARH", "VOLTAS",
)

NIFTY_100 = tuple(dict.fromkeys((*NIFTY_50, *NIFTY_100_EXTRA)))
NIFTY_200 = tuple(dict.fromkeys((*NIFTY_100, *NIFTY_200_EXTRA)))
NIFTY_500_SEED = NIFTY_200
FNO_STOCKS = tuple(dict.fromkeys((*NIFTY_50, *FNO_EXTRA)))


@dataclass(frozen=True)
class UniverseConfig:
    nifty_50: tuple[str, ...] = NIFTY_50
    nifty_100: tuple[str, ...] = NIFTY_100
    nifty_200: tuple[str, ...] = NIFTY_200
    nifty_500_seed: tuple[str, ...] = NIFTY_500_SEED
    fno_stocks: tuple[str, ...] = FNO_STOCKS


UNIVERSE_CONFIG = UniverseConfig()
